[package]
name = "sustechcourse"
version = "0.1.0"
authors = ["sorz <me@sorz.org>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
select = "0.4"
failure = "0.1.5"
actix-web = "0.7.19"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.6.1"
log = "0.4.6"